services:
  kafkaproducerservice:
    image: kafkaproducerservice
    build:
      context: .
      dockerfile: ./Dockerfile.prod
    environment:
      NODE_ENV: production
    ports:
      - 3000:3000
